// ═══════════════════════════════════════
// Aries V10 — Seed Data Generator
// ═══════════════════════════════════════

function seededRand(seed) {
  return function () {
    seed = (seed * 16807) % 2147483647;
    return (seed - 1) / 2147483646;
  };
}
const rng = seededRand(42);

const METHODS = ["GET", "POST", "PUT", "DELETE", "PATCH", "GET", "GET", "POST"];
const DOMAINS = [
  { prefix: "/api/v1/patients", resources: ["", "/search", "/{id}", "/{id}/insurance", "/{id}/allergies", "/{id}/medications", "/{id}/appointments", "/{id}/vitals", "/{id}/labs", "/{id}/notes", "/{id}/referrals", "/{id}/billing", "/{id}/documents"] },
  { prefix: "/api/v1/prescriptions", resources: ["", "/{id}", "/{id}/refill", "/{id}/transfer", "/{id}/verify", "/{id}/adjudicate", "/{id}/label", "/{id}/dispense", "/queue", "/search", "/pending"] },
  { prefix: "/api/v1/orders", resources: ["", "/{id}", "/{id}/items", "/{id}/shipping", "/{id}/payment", "/{id}/cancel", "/{id}/refund", "/{id}/track", "/bulk", "/search"] },
  { prefix: "/api/v1/inventory", resources: ["", "/check", "/{id}", "/{id}/reserve", "/{id}/release", "/reorder", "/audit", "/locations", "/{id}/history", "/alerts"] },
  { prefix: "/api/v1/claims", resources: ["", "/{id}", "/{id}/submit", "/{id}/status", "/{id}/appeal", "/{id}/attachments", "/batch", "/era", "/remit", "/search"] },
  { prefix: "/api/v1/providers", resources: ["", "/{id}", "/{id}/schedule", "/{id}/credentials", "/{id}/npi-verify", "/search", "/{id}/patients", "/{id}/referrals"] },
  { prefix: "/api/v1/auth", resources: ["/login", "/logout", "/refresh", "/mfa/verify", "/mfa/enroll", "/password/reset", "/sessions", "/keys"] },
  { prefix: "/api/v1/notifications", resources: ["", "/send", "/batch", "/{id}", "/{id}/read", "/preferences", "/templates", "/webhooks"] },
  { prefix: "/api/v1/reports", resources: ["/daily", "/weekly", "/monthly", "/custom", "/{id}", "/export", "/schedule", "/dashboard"] },
  { prefix: "/api/v1/formulary", resources: ["", "/search", "/{id}", "/{id}/alternatives", "/{id}/coverage", "/{id}/prior-auth", "/tiers", "/updates"] },
];
const TIMES = ["12ms", "25ms", "38ms", "50ms", "75ms", "90ms", "120ms", "150ms", "200ms", "350ms", "500ms", "750ms", "1.2s"];
const FTYPES = ["string", "integer", "boolean", "number", "array", "object", "uuid", "date-time", "email", "enum"];
const FREQ = ["id", "type", "status", "created_at", "updated_at"];
const FOPT = ["name", "description", "code", "value", "amount", "quantity", "date", "email", "phone", "address", "city", "state", "zip", "country", "notes", "tags", "metadata", "priority", "category", "source", "reference_id", "external_id", "is_active", "expires_at", "version"];

function genSchema(fc) {
  const f = [];
  for (let i = 0; i < Math.min(fc, FREQ.length); i++) f.push({ name: FREQ[i], type: FTYPES[Math.floor(rng() * FTYPES.length)], required: true });
  for (let j = 0; j < fc - FREQ.length && j < FOPT.length; j++) f.push({ name: FOPT[j], type: FTYPES[Math.floor(rng() * FTYPES.length)], required: rng() > 0.6 });
  return f;
}

export function genEndpoints(n) {
  const eps = [];
  let id = 0;
  for (const d of DOMAINS) {
    for (const r of d.resources) {
      if (id >= n) break;
      let method = METHODS[Math.floor(rng() * METHODS.length)];
      if (r.includes("{id}") && method === "POST") method = "PUT";
      if (r === "" && rng() > 0.5) method = "POST";
      const fc = Math.floor(rng() * 40) + 5;
      eps.push({ id: "r" + id, method, path: d.prefix + r, time: TIMES[Math.floor(rng() * TIMES.length)], fieldCount: fc, schema: genSchema(fc) });
      id++;
    }
  }
  while (eps.length < n) {
    const fc = Math.floor(rng() * 30) + 5;
    eps.push({ id: "r" + eps.length, method: METHODS[Math.floor(rng() * METHODS.length)], path: "/api/v2/resource-" + eps.length, time: TIMES[Math.floor(rng() * TIMES.length)], fieldCount: fc, schema: genSchema(fc) });
  }
  return eps.slice(0, n);
}

const PROBE_PREFIX = ["Validates", "Probes", "Checks", "Verifies", "Ensures", "Confirms"];
const PROBE_ACTION = ["CRUD operations", "boundary conditions", "auth flow", "error handling", "timeout behavior", "concurrent access", "data integrity", "pagination", "rate limiting", "field validation", "search filters", "bulk operations", "webhook delivery", "cache invalidation", "retry logic", "idempotency", "input sanitization", "permission checks", "audit logging", "rollback behavior"];
const AI_DESCS = [
  "AI-generated probe covering positive and negative scenarios with full request/response validation, status code checks, and payload schema verification.",
  "Automatically generated from API schema analysis. Covers edge cases including null values, empty strings, overflow values, and malformed payloads.",
  "Generated by Aries AI engine based on endpoint contract. Includes authentication, authorization, and data integrity assertions.",
  "AI-inferred probe from OpenAPI spec. Validates response structure, error codes, rate limit headers, and pagination consistency.",
  "Machine-generated coverage for happy path, error path, and boundary conditions. Includes retry and timeout behavior validation.",
];

export function genTests(endpoints) {
  const tests = [];
  let id = 0;
  endpoints.forEach((ep) => {
    const count = Math.floor(rng() * 3) + 1;
    for (let i = 0; i < count && id < 400; i++) {
      tests.push({
        id: "t" + id, ep: ep.id,
        name: PROBE_PREFIX[Math.floor(rng() * PROBE_PREFIX.length)] + " " + PROBE_ACTION[Math.floor(rng() * PROBE_ACTION.length)] + " for " + ep.path.split("/").pop().replace("{id}", "record"),
        desc: AI_DESCS[Math.floor(rng() * AI_DESCS.length)],
        pos: Math.floor(rng() * 5) + 1, neg: Math.floor(rng() * 4),
        review: ["approved", "pending", "pending", "approved", "rejected", "pending", "approved", "approved"][Math.floor(rng() * 8)],
        aiConf: Math.floor(rng() * 35) + 65, aiGenerated: true,
      });
      id++;
    }
  });
  return tests;
}

export function genSuites(n, tests) {
  const names = ["smoke", "regression", "e2e", "integration", "nightly", "hourly-health", "load-test", "security-scan", "compliance", "perf-bench", "chaos", "canary", "staging-gate", "prod-verify", "rollback", "dr-test", "migration", "api-contract", "schema-check", "auth-flow"];
  const domainNames = ["patient", "order", "rx", "claim", "inventory", "provider", "auth", "notify", "report", "formulary", "billing", "shipping", "payment", "search", "admin", "audit", "cache", "queue", "webhook", "scheduler"];
  const freqs = ["Hourly", "Daily", "Weekly", "On Deploy", "Bi-Weekly"];
  const suites = [];

  for (let i = 0; i < n; i++) {
    let nm = domainNames[i % domainNames.length] + "-" + names[i % names.length];
    if (i >= 20) nm += "-" + (Math.floor(i / 20) + 1);
    const tIds = [];
    for (let j = 0; j < Math.floor(rng() * 8) + 2; j++) {
      const tid = "t" + Math.floor(rng() * tests.length);
      if (!tIds.includes(tid)) tIds.push(tid);
    }
    const runs = [];
    for (let k = 0; k < Math.floor(rng() * 15) + 3; k++) {
      runs.push({ s: rng() > 0.2 ? "pass" : "fail", d: (Math.floor(rng() * 12) + 1) + "m " + Math.floor(rng() * 59) + "s" });
    }
    const hour = Math.floor(rng() * 24);
    const min = Math.floor(rng() * 4) * 15;
    suites.push({
      id: "s" + i, name: nm, tests: tIds, runs, freq: freqs[Math.floor(rng() * freqs.length)],
      schedule: String(hour).padStart(2, "0") + ":" + String(min).padStart(2, "0") + " UTC",
      lastRun: Math.floor(rng() * 48) + "h ago", nextRun: "Scheduled",
      enabled: rng() > 0.15,
      incident: rng() > 0.92 ? { key: "INC" + Math.floor(rng() * 99999), status: rng() > 0.5 ? "Investigating" : "Monitoring" } : null,
    });
  }
  return suites;
}

// Pre-generate data
export const ENDPOINTS = genEndpoints(100);
export const INIT_TESTS = genTests(ENDPOINTS);
export const INIT_SUITES = genSuites(100, INIT_TESTS);
